# Generated by Django 3.0.5 on 2021-10-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=100)),
            ],
        ),
    ]
