# Generated by Django 3.0.5 on 2021-11-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultID', models.AutoField(primary_key=True, serialize=False)),
                ('studentID', models.IntegerField()),
                ('examID', models.IntegerField()),
                ('ansAttempt', models.IntegerField()),
                ('correctAns', models.IntegerField()),
                ('GPA', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('sID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('sdID', models.IntegerField()),
                ('examID', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentexam',
            name='endAttempt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='creditHour',
            field=models.IntegerField(null=True),
        ),
    ]
