# Generated by Django 3.0.5 on 2021-10-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
