# Generated by Django 3.0.5 on 2021-10-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0002_instructor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructorContact',
            field=models.CharField(max_length=11),
        ),
    ]
