# Generated by Django 3.0.5 on 2021-10-19 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentContact', models.CharField(max_length=11)),
                ('studentAddress', models.CharField(max_length=300)),
                ('studentEmail', models.CharField(max_length=100)),
                ('studentGender', models.CharField(max_length=1)),
                ('studentIC', models.CharField(max_length=12)),
                ('studentDOB', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
